### PR TITLE
swift5.5 concurrency support (async await)

### PR DESCRIPTION
**Pull request by hootigger**
can use async/await in swift5.5(xcode13)
Package.swift in Target config.
```swift
swiftSettings: [
                .unsafeFlags([
                    "-Xfrontend", "-disable-availability-checking", // ignore concurrency api check
                    "-Xfrontend", "-enable-experimental-concurrency",
                ]),
            ]
```

### CODE REVIEW

**Comment by hootigger** [comment]
and update TG Bot API 5.3 & fix generate_wrappers.rb

**Comment by givip** [comment]
Awesome changes

**Comment by givip** [comment]
> and update TG Bot API 5.3 & fix generate_wrappers.rb

Do you want to be co-maintainer of this package? Please write me in telegram @givip

**Comment by hootigger** [comment]
> > and update TG Bot API 5.3 & fix generate_wrappers.rb
> 
> Do you want to be co-maintainer of this package? Please write me in telegram @givip

yes. I'll contact you in telegram.

**Pull request merged**
