### PR TITLE
Add Support for the API of Poll 2.0 Features

### PR DESCRIPTION
**Pull request by uetcis**
As the title, this pull request adds support for poll 2.0 API.

### CODE REVIEW

**Comment by givip** [comment]
Thats great! For future, try to use my scripts for API generation, that does that automatically.
/API/download_api_docs.sh
/API/generate_wrappers.rb

**Comment by uetcis** [comment]
Oh I'm sorry that I didn't know the existence of these scripts. Do I need to revert my manual changes?

**Comment by givip** [comment]
Will be more consistent if we keep generated sources generated. Moreover, we will keep script correctness updated. Thanks

**Comment by uetcis** [comment]
It seems the destination folder in the API generating script is wrong and I fixed it.
And BTW it seems there's room for improvement for the auto-generated API, for example the poll type would be better represented as an enum instead simply a string. Moreover, it is not conforming to the official Swift [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) that:
> Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:
> ```swift
> var utf8Bytes: [UTF8.CodeUnit]
> var isRepresentableAsASCII = true
> var userSMTPServer: SecureSMTPServer
> ```

An example of the violation would be the generated variable name `correctOptionId`, which should be `correctOptionID` according to the guide.

**Comment by uetcis** [comment]
Why are there so many conflicts....

**Comment by givip** [comment]
> It seems the destination folder in the API generating script is wrong and I fixed it.
> And BTW it seems there's room for improvement for the auto-generated API, for example the poll type would be better represented as an enum instead simply a string. Moreover, it is not conforming to the official Swift [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) that:
> 
> > Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:
> > ```swift
> > var utf8Bytes: [UTF8.CodeUnit]
> > var isRepresentableAsASCII = true
> > var userSMTPServer: SecureSMTPServer
> > ```
> 
> An example of the violation would be the generated variable name `correctOptionId`, which should be `correctOptionID` according to the guide.

Good catch, but for script it will be impossible to distinguish acronyms and initialisms. So for now I just translate `snake_case` to swift friendly `camelCase`.

Lets keep generated API clean, without additional logic. This helps us to update our API wrappers (methods, models, docs) very quickly .

If you want improve framework by some additional helpers, you could write them and add to PR separately.

About conflicts, I'll check.

**Comment by givip** [comment]
Please use this git patch for your branch.
And then rebase on `master`.

```
From 6fda1b359f8e67d5f7d6da4c3eebddee823114fd Mon Sep 17 00:00:00 2001
From: givip <pataridzegivi@gmail.com>
Date: Mon, 3 Feb 2020 18:18:06 +0400
Subject: [PATCH] Fix

---
 API/generate_wrappers.rb                                 | 9 +++++++--
 Sources/Telegrammer/Bot/Telegram/Models/PollAnswer.swift | 4 ++--
 2 files changed, 9 insertions(+), 4 deletions(-)

diff --git a/API/generate_wrappers.rb b/API/generate_wrappers.rb
index 287013d..5c41112 100755
--- a/API/generate_wrappers.rb
+++ b/API/generate_wrappers.rb
@@ -213,8 +213,10 @@ def convert_type(var_name, var_desc, var_type, type_name, var_optional)
 		suffix = is64bit ? '64' : ''
 		return "Int#{suffix}?"
 	when ['Integer', false]
-		is64bit = var_name.include?("user_id") || var_name.include?("chat_id") || var_desc.include?("64 bit integer") ||
-							(type_name == 'User' && var_name == 'id')
+		is64bit = var_name.include?("user_id") ||
+                  var_name.include?("chat_id") ||
+                  var_desc.include?("64 bit integer") ||
+                  (type_name == 'User' && var_name == 'id')
 		suffix = is64bit ? '64' : ''
 		return "Int#{suffix}"
 	when ['Float number', true], ['Float', true]
@@ -242,6 +244,9 @@ def convert_type(var_name, var_desc, var_type, type_name, var_optional)
 			end
 		elsif var_type.start_with?(array_prefix) then
 			var_type.slice! array_prefix
+            if var_type == 'Integer' then
+                var_type = 'Int'
+            end
 			# Present optional arrays as empty arrays
 			if var_optional then
 				return "[#{var_type}]?"
diff --git a/Sources/Telegrammer/Bot/Telegram/Models/PollAnswer.swift b/Sources/Telegrammer/Bot/Telegram/Models/PollAnswer.swift
index 04f470e..3c707e5 100644
--- a/Sources/Telegrammer/Bot/Telegram/Models/PollAnswer.swift
+++ b/Sources/Telegrammer/Bot/Telegram/Models/PollAnswer.swift
@@ -23,10 +23,10 @@ public final class PollAnswer: Codable {
     public var user: User
 
     /// 0-based identifiers of answer options, chosen by the user. May be empty if the user retracted their vote.
-    public var optionIds: [Integer]
+    public var optionIds: [Int]
 
 
-    public init (pollId: String, user: User, optionIds: [Integer]) {
+    public init (pollId: String, user: User, optionIds: [Int]) {
         self.pollId = pollId
         self.user = user
         self.optionIds = optionIds
-- 
2.17.1

```

**Comment by uetcis** [comment]
I first ran `git apply` and committed, which resulted the commit above. Then I tried `git rebase`, getting the following:
<details>
<summary>Error Message</summary>

```
First, rewinding head to replay your work on top of it...
Applying: Add Some of The New Poll Attributes
Applying: Add PollAnswer
Applying: Add PollAnswerHandler
Applying: Add All Left New Poll Properties
Applying: Fix Destination in API Generating Script
Using index info to reconstruct a base tree...
M	API/generate_wrappers.rb
Falling back to patching base and 3-way merge...
Auto-merging API/generate_wrappers.rb
No changes -- Patch already applied.
Applying: Update Generated API
Using index info to reconstruct a base tree...
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+deleteChatPhoto.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+getUpdates.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+kickChatMember.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+restrictChatMember.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendAudio.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendInvoice.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendPoll.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendSticker.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatDescription.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatPhoto.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatTitle.swift
M	Sources/Telegrammer/Bot/Telegram/Methods/Bot+setWebhook.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Animation.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Audio.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Chat.swift
M	Sources/Telegrammer/Bot/Telegram/Models/ChatMember.swift
M	Sources/Telegrammer/Bot/Telegram/Models/ChatPhoto.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Document.swift
M	Sources/Telegrammer/Bot/Telegram/Models/File.swift
M	Sources/Telegrammer/Bot/Telegram/Models/InlineQueryResultAudio.swift
M	Sources/Telegrammer/Bot/Telegram/Models/InlineQueryResultCachedAudio.swift
M	Sources/Telegrammer/Bot/Telegram/Models/PassportFile.swift
M	Sources/Telegrammer/Bot/Telegram/Models/PhotoSize.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Sticker.swift
M	Sources/Telegrammer/Bot/Telegram/Models/StickerSet.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Video.swift
M	Sources/Telegrammer/Bot/Telegram/Models/VideoNote.swift
M	Sources/Telegrammer/Bot/Telegram/Models/Voice.swift
.git/rebase-apply/patch:284: trailing whitespace.

.git/rebase-apply/patch:352: trailing whitespace.

warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Voice.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Voice.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/VideoNote.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/VideoNote.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Video.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Video.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Sticker.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Sticker.swift
Removing Sources/Telegrammer/Bot/Telegram/Models/PollType.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/PhotoSize.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/PhotoSize.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/PassportFile.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/PassportFile.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/File.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/File.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Document.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Document.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/ChatPhoto.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/ChatPhoto.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/ChatMember.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/ChatMember.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Chat.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Chat.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Audio.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Audio.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Models/Animation.swift
CONFLICT (content): Merge conflict in Sources/Telegrammer/Bot/Telegram/Models/Animation.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+setWebhook.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatTitle.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatPhoto.swift
CONFLICT (add/add): Merge conflict in Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatPermissions.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatPermissions.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+setChatDescription.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendSticker.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendPoll.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendInvoice.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+sendAudio.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+restrictChatMember.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+kickChatMember.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+getUpdates.swift
Auto-merging Sources/Telegrammer/Bot/Telegram/Methods/Bot+deleteChatPhoto.swift
error: Failed to merge in the changes.
Patch failed at 0006 Update Generated API
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

</details>

**Comment by givip** [comment]
@CaptainYukinoshitaHachiman If you are not agains, I'll add this changes by myself

**Comment by uetcis** [comment]
Sure it'll be fine

**Comment by givip** [comment]
Oh, The reason is that we are not updating version 0.5.4 anymore. We should add those updates to version 1.0.0.
I'll update that

**Pull request closed without merging**
